## An ACTION for computing the path between the points
## the resulting path will be a list of of points.

# GOAL
# The first position of the path
geometry_msgs/Point start
# The last position of the path
geometry_msgs/Point goal
---
# RESULT
# The list of points composing the path
geometry_msgs/Point[] path
---
# FEEBACK
# There is no feedback
