## An ACTION for making the robot move along a path
## composed of a list of points.

# GOAL
# The list of points composing the path
geometry_msgs/Point[] path
---
# RESULT
# The actual final position of the robot may be different
# than the last position of the path. This contains the 
# actual final position of the robot.
geometry_msgs/Point position
---
# FEEBACK
# The current position of the robot
geometry_msgs/Point position
